# Docker Compose file for a Baikal server
# admin login name: "admin" & pw will be set upon first login to webinterface on port 7080
# If baikal is not happy with folder permissions (it will tell you in the web interface), use the following commands to fix: [source](https://github.com/ckulka/baikal-docker/blob/master/examples/docker-compose.localvolumes.yaml)
# doas chown -R 101:101 /nas/data/programdata/baikal/specific
# doas chown -R 101:101 /nas/data/programdata/baikal/config


version: "2"
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "7080:80" # port 7080 set by me and configured in nginx reverse proxy manager
    volumes:
      - /nas/data/programdata/baikal/config:/var/www/baikal/config
      - /nas/data/programdata/baikal/specific:/var/www/baikal/Specific
